### ISSUE TITLE
use dev/nightly on all emulator

### ISSUE THREAD

**Issue by super-lurker** [FlotterCodername/superelixier-updater#17]
pcsx2 - https://pcsx2.github.io/downloads.html
pls use avx2 64

PPSSPP - https://buildbot.orphis.net/ppsspp/

**Comment by FlotterCodername** [comment]
Good pointers, thank you :)
I'll have a go at this after work

**Comment by super-lurker** [comment]
while your at it, can you also add duckstation? thanks :)

**Comment by FlotterCodername** [comment]
All done, check out [Preview 12](https://github.com/FlotterCodername/superelixier-updater/releases/tag/preview-12)! 😁
