### ISSUE TITLE
more apps

### ISSUE THREAD

**Issue by super-lurker** [FlotterCodername/superelixier-updater#21]
librewolf (portable)
a firefox fork
https://gitlab.com/librewolf-community/browser/windows/-/releases

streamlink
https://github.com/streamlink/streamlink

Freetube (portable)
An Open Source YouTube app for privacy
https://github.com/FreeTubeApp/FreeTube

tixati (portable)
best torrent client
https://www.tixati.com/download/portable.html

paint.net
image editor
https://www.dotpdn.com/downloads/pdn.html

oceanaudio (portable)
audio editor
https://www.ocenaudio.com/download

foobar2000 (portable)
best audio player
https://www.foobar2000.org/download

**Comment by FlotterCodername** [comment]
This repo now has a template for app request, so I've taken these requests and created a ticket for each:
#22 LibreWolf
#23 Streamlink
#24 FreeTube
#25 Tixati
#26 paint.net
#27 ocenaudio
#28 foobar2000
Closes #21
