### ISSUE TITLE
[APP] FreeTube

### ISSUE THREAD

**Issue by FlotterCodername** [FlotterCodername/superelixier-updater#24]
### App name
FreeTube

### App description
An Open Source YouTube app for privacy

### Hosted at
<Click appropriate box after submitting issue>

- [ ] AppVeyor
- [x] GitHub
- [ ] Other service: SERVICE_NAME_HERE
- [ ] Project website

URL: https://github.com/FreeTubeApp/FreeTube
<AppVeyor or GitHub is preferred over project websites>

**Comment by super-lurker** [comment]
is there anyway to use two folder output on a single config file?

**Comment by FlotterCodername** [comment]
Not sure if understand it correctly! But this works.
```json
{
  "C:/PortableApps": [
    "dbeaver"
  ],
  "D:/Games/Emulators": [
    "citra-canary",
    "citra-nightly"
  ]
}
```
If you mean multiple installs of the same app... I frankly don't know off the top of my head what would happen
