### ISSUE TITLE
[BUG] PPSSPP Dev Build seem to be broken

### ISSUE THREAD

**Issue by super-lurker** [FlotterCodername/superelixier-updater#33]
### Describe the bug
PPSSPP Dev Build seem to be broken, something about url not matching?

### To Reproduce
1. update ppsspp
2. error

### Expected behavior
successful update

### My environment
W10 21H1 x64

**Comment by FlotterCodername** [comment]
The correct URL is still found, but it seems it is now locked behind Google Analytics tracking. The updater doesn't do JavaScript interpretation, so it gets thrown for a loop [on this page](https://buildbot.orphis.net/ppsspp/index.php?m=detail&rev=v1.12.3-980-g3bfab6326&platform=windows-amd64).
I'm a afraid this is out of scope. As a rule of thumb, if curl can't download the URL, this app will not be able to either.
Even if I wanted to play nice with Google Analytics (which I don't), I'd have to inspect a bunch of 3rdparty JavaScript, probably on a per-updatable-app basis.

I just saw that PPSSPP uses GitHub Actions for Building. I'll be looking implementing a generic GitHub Actions build grabber instead.
```
################################
# PPSSPP Development: Updating #
################################
Downloading file from: https://buildbot.orphis.net/ppsspp/index.php?m=dl&rev=v1.12.3-980-g3bfab6326&platform=windows-amd64
Error: Failed to find URL on redirect
Error: Failure downloading or extracting this app
```

**Comment by super-lurker** [comment]
heck ye, fuck google
