### ISSUE TITLE
[BUG] RPCS3 not downloading the latest build

### ISSUE THREAD

**Issue by super-lurker** [FlotterCodername/superelixier-updater#34]
### Describe the bug
superelixier claims no new update, when in reality its 6month old behind. wtf

### To Reproduce
update rpcs3 via superelixier 

### Expected behavior
update rpcs3 

### My environment
-win 10 x64 Enterprise LTSC Edition
-21H2

**Comment by FlotterCodername** [comment]
Looks like they made the rolling release builds private around early March this year. So now the definition gets the last one they have on GitHub.
Here's the new definition, replace contents of `superelixier-updater/definitions/rpcs3.json` with this:
```json
{
  "info": {
    "gist": "Emulates the Sony PlayStation 3.",
    "category": "Emulators"
  },
  "name": "RPCS3",
  "url": "https://rpcs3.net/download",
  "ver_scheme_type": "id",
  "ver_scheme_re": "<span>Build <span class='version-buildversion'>(.*?)</span></span>",
  "ver_scheme_spec": 1,
  "blob_permalink": "https://rpcs3.net/latest-windows",
  "blob_unwanted": [],
  "appdatas": [],
  "repo": "html"
}
```

**Comment by FlotterCodername** [comment]
Heads up @super-lurker: Update needed for this to work correctly. https://github.com/FlotterCodername/superelixier-updater/releases/tag/preview-13
