### ISSUE TITLE
[APP] xemu

### ISSUE THREAD

**Issue by super-lurker** [FlotterCodername/superelixier-updater#36]
### App name
xemu

### App description
Original Xbox Emulator for Windows, macOS, and Linux

### Hosted at
<Click appropriate box after submitting issue>

- [ ] AppVeyor
- [x] GitHub
- [ ] Other service: SERVICE_NAME_HERE
- [ ] Project website

URL: 
https://github.com/mborgerson/xemu

**Comment by FlotterCodername** [comment]
It's in :)
```json
{
  "info": {
    "gist": "Emulates the Microsoft Xbox.",
    "category": "Emulators"
  },
  "name": "xemu",
  "user": "mborgerson",
  "project": "xemu",
  "blob_re": "^xemu-win-release\\.zip$",
  "blob_unwanted": [],
  "appdatas": [],
  "repo": "github"
}
```
