### ISSUE TITLE
[APP] Snes9x

### ISSUE THREAD

**Issue by Albin-Xavier** [FlotterCodername/superelixier-updater#38]
### App name
<name of the app to add>Snes9x

### App description
<Oneliner description of app>Super Nintendo Entertainment System Emulator

### Hosted at
<Click appropriate box after submitting issue>

- [ ] AppVeyor
- [x] GitHub
- [ ] Other service: SERVICE_NAME_HERE
- [ ] Project website

URL: 
<AppVeyor or GitHub is preferred over project websites>https://github.com/snes9xgit/snes9x

**Comment by FlotterCodername** [comment]
Added!
```json
{
  "info": {
    "gist": "Emulates the Super Nintendo Entertainment System.",
    "category": "Emulators"
  },
  "name": "Snes9x",
  "user": "snes9xgit",
  "project": "snes9x",
  "blob_re": "^snes9x-.*?-win32-x64\\.zip$",
  "blob_unwanted": [],
  "appdatas": [],
  "repo": "github"
}
```
