### ISSUE TITLE
[APP] MelonDS

### ISSUE THREAD

**Issue by Albin-Xavier** [FlotterCodername/superelixier-updater#39]
### App name
<name of the app to add>MelonDS

### App description
<Oneliner description of app>Nintendo DS Emulator

### Hosted at
<Click appropriate box after submitting issue>

- [ ] AppVeyor
- [x] GitHub
- [ ] Other service: SERVICE_NAME_HERE
- [ ] Project website

URL: 
<AppVeyor or GitHub is preferred over project websites>https://github.com/Arisotura/melonDS

**Comment by FlotterCodername** [comment]
Done. This will be in the next release.
You can also drop this file in your definitions folder if you don't want to wait:
https://github.com/FlotterCodername/superelixier-updater/blob/main/definitions/melonds.json
