### ISSUE TITLE
[BUG] blender and keepassXC

### ISSUE THREAD

**Issue by super-lurker** [FlotterCodername/superelixier-updater#40]
### Describe the bug
update failed
### To Reproduce

![sshot-2022-04-17-12-15-30](https://user-images.githubusercontent.com/13076066/163700387-e5b363a0-1f10-4805-a2ae-7a2e1b1ffafe.png)

**Comment by FlotterCodername** [comment]
Sorry for the long radio silence. These has been fixed in https://github.com/FlotterCodername/superelixier-updater/releases/tag/0.1.0
