### ISSUE TITLE
[BUG] RPCS3 fails to download

### ISSUE THREAD

**Issue by Lycaon37** [FlotterCodername/superelixier-updater#42]
### Describe the bug
When attempting to update RPCS3 via Superelixier, receive message stating "No matching downloads for the latest version". Similar behavior occurs when attempting to install RPCS3. Appears to no longer be able to download RPCS3.

### To Reproduce
1. Add "RPCS3" to local.json in any installation directory.
2. Run Superelixier

### Expected behavior
RPCS3 to be downloaded and installed.

### My environment
<please complete the following information>

- *OS* is Windows 11
- *Version* is Superelixier preview-13

**Comment by FlotterCodername** [comment]
Sorry for the long radio silence. This has been fixed in https://github.com/FlotterCodername/superelixier-updater/releases
